CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE customer(
cID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(25),
cAge TINYINT
);
CREATE TABLE Orders(
oID INT PRIMARY KEY AUTO_INCREMENT,
oDate DATETIME,
oTotalPrice INT,
cID INT,
FOREIGN KEY(cID)REFERENCES customer(cID)
);
CREATE TABLE product(
pID INT PRIMARY KEY AUTO_INCREMENT,
pName VARCHAR(25),
pPrice INT
);
CREATE TABLE OrderDetail(
odQTY INT,
oID INT,
pID INT,
FOREIGN KEY(oID)REFERENCES orders(oID),
FOREIGN KEY(pID)REFERENCES product(pID)
)